### ISSUE TITLE
Solar Envelope user request

### ISSUE THREAD

**Issue by boris-p** [ladybug-tools/ladybug-legacy#199]
Hello everybody, 
recently a user posted in the LB + HB forum regarding the new solar envelope component - http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1404397&xg_source=msg

To try and sum up my conclusions from that , I think there are two main points - 
1. There should be an option to filter relevant suns also based on their (2d) angle in relation to the facade. That is an issue that I've already been working on and shouldn't take long to implement. To try and illustrate - 
![relavent_suns-10](https://cloud.githubusercontent.com/assets/3728381/11319308/2d81a4e0-9072-11e5-9306-aa02204ae1db.jpg)
We could set an angle as an additional input parameter, smaller than that angle the sun would be ignored in the calculation, the logic being that that sun access brings little advantage but restricts the envelope.
2. There should be an option to combine different envelopes to one, either taking the highest points from all the envelopes or the lowest ones. In such a way we could run the solar envelope component with different conditions and combine them any way we see fit. I've written a small component which does just that (the rightmost in the example file) - http://hydrashare.github.io/hydra/viewer?owner=boris-p&fork=hydra&id=LadyBug_Combine_solarEnvelopes (hope i'm not abusing the purpose of hydra, btw it's awesome!) 
The component is pretty simple, but I could imagine situations where people might want to combine a few versions of envelopes into one, and maybe it is worth providing users with an easy option to do that, what do you think?

In any case i'll update the user as well and see if he has further suggestions or thoughts.

/b

**Comment by mostaphaRoudsari** [comment]
Hi @boris-p! Thank you for summarizing the issues.
1. Sound like a great feature and brings more flexibility.
2. That's how Hydra is intended to be used. Nice work.

**Comment by chriswmackey** [comment]
@boris-p ,
Both ideas are great.  You are making the early visions of Hydra a reality.  If you would like to make the "combine envelopes" component a part of the suite, feel free to send a pull request that places it either in WIP or (since this seems like a smaller utility component), the Extra Tab with AdditionalHelpFromDocStrings = "0".
-Chris

**Comment by boris-p** [comment]
@mostaphaRoudsari, and @chriswmackey . I created a pull request (201. before that I created another pull request with not up to date code, sorry)
If you could briefly take a look at the component  and tell me if you think it fits the standard that would be great.
Regarding the first issue, it might take a bit longer as it involves some changes in the actual solar envelope component and I wanted to make more extensive tests.

**Comment by mostaphaRoudsari** [comment]
@boris-p thanks. I merged the PR. Looking forward to the next one.

**Comment by AntoineDao** [comment]
I'm assuming I can remove @boris-p 's assignment as this issue is 4 years old.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, @boris-p do we still need such feature? If I'm not mistaken a couple of people have developed workflows which does this - I have see a number of papers.

**Comment by boris-p** [comment]
i'm pretty sure that it's already irrelevant. 
Just checked and the functionality was added in pr 201

**Comment by chriswmackey** [comment]
Also, I think the first issue was partly addressed by @AntonelloDN 's [component that allows you to get a set of sun vectors filtered based on angle above the horizon](https://mostapharoudsari.gitbooks.io/ladybug-primer/content/text/components/SunriseSunset.html).  I know it's a little different than exactly what you were describing here @boris-p but it has a similar impact of not making the envelope overly-restrictive.  I agree that this issue should just be closed.
