### ISSUE TITLE
Ladybug_Analysis Period (feature request)

### ISSUE THREAD

**Issue by CsillaVG** [ladybug-tools/ladybug-legacy#461]
Hi,

First of all thank you and the other contributors for all the Ladybug-related scripts! They are awesome!
I have noticed that when the analysis period is passed to Energy Plus, a year is attached. I wonder if it would be possible to specify a year already in Grasshopper. Thanks!

Csilla

**Comment by chriswmackey** [comment]
@CsillaVG ,

Sorry for the very late response.  This feature is relatively new to EnergyPlus but it unfortunately is set up a bit counter to how people typically use energy modeling.  It is also counter to how honeybee (and OpenStudio) are set up: to essentially run generic years or run TMY, which are composed of data taken from a range of different years.

What we (and OpenStudio SDK) will expose is the ability to set whether the simulation is for a leap year and the ability to set the start day of the week, which should be enough to allow you to run any year that you like.  However, we don't have plans to enable the multi-year simulations that this change to EnergyPlus was essentially made to do.  You will see that the new ladybug[+] python library is already set up to handle leap year data and so this capability is something that you can expect in the next revision of Ladybug Tools (a Grasshopper release is 6-12 months down the line).

**Comment by CsillaVG** [comment]
Thank you!
