### ISSUE TITLE
Legend scale not working in windRose component

### ISSUE THREAD

**Issue by ayezioro** [ladybug-tools/ladybug-legacy#473]
Hi,
I believe i've found a small bug in the windRose, where it is not accepting changes in the legendScale parameter while a legendPar component is plugged.
In the code below you can see where it is happening. The commented line is the original. The line above that is at it should be.
It starts at line 703.
@chris or @devngc , it will be easier if one of you fix it (than if i do).
Thanks,
-A.

>             # initiate legend parameters
>             overwriteScale = False
>             if legendPar == []: overwriteScale = True
>             elif legendPar[-1] == None: overwriteScale = False
>             ####elif legendPar[-1] == None: overwriteScale = True

**Comment by devngc** [comment]
Hi Abraham,
Thanks for pointing. I will look into this.
Thank you!

**Comment by devngc** [comment]
@ayezioro, Can you please close the issue?
