### ISSUE TITLE
New tab / category structure - not all components migrated

### ISSUE THREAD

**Issue by ayezioro** [ladybug-tools/ladybug-legacy#485]
Hi,
I've updated to the last version on the github ([This one](https://github.com/ladybug-tools/ladybug-legacy/commit/381dcff506e1e4af1ad988f6b0e6f8a4b2fb35be)).
The folder identified by GH to upload them is now LB-Legacy or HB-Legacy, as opposed to the previous Ladybug or Honeybee.
This works fine for most of the components, but still there are some, developed in C++ that are not yet migrated corrrectly and still preserve the old folder name.
They are:
Ladybug:
Ladybug_ImageViewer - @MingboPeng 
Ladybug_SortByLayers - @MingboPeng 
False Start Toggle
and @AntonelloDN all ladybut_ENVIMET located at the WIP tab.
Honeybee:
Honeybee_IntersectMassII - @saeranv?
Honeybee_Item Selector
Honeybee_ReadAnnualResultsIII - @MingboPeng 

Hopefully they will be updated soon so alll the package will be fully functional.

Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

We are aware of all of the C# components and most of them were written by @MingboPeng and @AntonelloDN . @MingboPeng  is aware of the change and is working on a new version of IronBug.

I think because @AntonelloDN has [a newer version of the envi-met components that he's released under dragonfly legacy](https://github.com/chriswmackey/Dragonfly/tree/master/envimet), we'll just say that the older version isn't distributed anymore, except in the very old Food4Rhino releases.

**Comment by AntonelloDN** [comment]
Hi @chriswmackey and @ayezioro,

Yes, we can remove old envimet components from Ladybug. It is better to have envimet stuff only under Dragonfly Legacy.

**Comment by mostaphaRoudsari** [comment]
> Yes, we can remove old envimet components from Ladybug. It is better to have envimet stuff only under Dragonfly Legacy.

@AntonelloDN, can you give me a list of the components? or remove them yourself and send a PR. I almost know which ones are the ones but I'm not confident.

Thank you @ayezioro for reporting the issue. This is a change to open up ladybug and honeybee tabs for the [+] libraries.

**Comment by AntonelloDN** [comment]
Hi @mostaphaRoudsari ,

components are:
<ul>
<li>Ladybug_ENVI-Met Building Terrain</li>
<li>Ladybug_ENVI-Met Display</li>
<li>Ladybug_ENVI-Met Find Output Folder</li>
<li>Ladybug_ENVI-Met Grid</li>
<li>Ladybug_ENVI-Met Manage Workspace</li>
<li>Ladybug_ENVI-Met Read Library</li>
<li>Ladybug_ENVI-Met Soil Plant Source</li>
<li>Ladybug_ENVI-Met Spaces</li>
</ul>

**Comment by mostaphaRoudsari** [comment]
Thank @AntonelloDN! I removed those and also removed "Ladybug_ENVI-Met Results Reader". https://github.com/ladybug-tools/ladybug-legacy/commit/65b56d98e97980fc9e5f987a5f94391e7615861c

**Comment by chriswmackey** [comment]
I know that @MingboPeng mostly addressed this as part of [this commit](https://github.com/ladybug-tools/ladybug-legacy/commit/13a33344ff3de6b076d4f40641e51579321cd3d6).

However, the False Start Toggle seems to be a part of the Ironbug.LBHB_Legacy.gha that everything got wrapped into and this component is still showing up in the Ladybug tab (as opposed to LB-Legacy):
![image](https://user-images.githubusercontent.com/5567574/83806343-5d9f4d80-a67f-11ea-8d29-f8e331848631.png)

Can you fix this @MingboPeng ?

**Comment by chriswmackey** [comment]
After clearing up some confusion, I think we can close out this issue thanks to this commit:
https://github.com/ladybug-tools/ladybug-legacy/commit/f2419397010ff34d1a1967629e512a795233d226
