### ISSUE TITLE
Ladybug_Sunlight Hours Analysis  period filter function wish

### ISSUE THREAD

**Issue by roxas358** [ladybug-tools/ladybug-legacy#486]
Due to the increasing density of buildings in the city, the occlusion situation is more complex. Generally, there are several buildings sheltered by the sheltered buildings, so the time period for the buildings to get sunshine is often discontinuous, and in some cases, there will be a few minutes or even shorter time period. 

I wish the "Ladybug_Sunlight Hours Analysis" could add a “Minimum Time Span filter” (MTS for short) allowing users to set a number in minute to control the minimum continuous sunshine time condition. While this function activated, for each test unit（point or mesh），only the continuous period not less than MTS shall pass the filter condition and be added to the sunlight time.

There are several reasons for not taking these short sunshine time periods into account: first, the sunshine quality of the short sunshine time period is poor; second, due to the limitation of data accuracy and software calculation accuracy, the errors that are easy to appear in the calculation are generally about a few minutes; in addition, in the actual observation, due to the influence of factors such as blurred shadow boundary and surrounding environment, etc It is difficult to judge and detect too short sunshine period. From the comparison of software calculation and actual observation, the deviation between the two is generally within 3.0min-5.0min, so the sunshine period less than 5.0min is uncertain and meaningless. This regulation is mainly from the point of view of convenient calculation. It is also reasonable for some cities to make local regulations on the minimum continuous sunshine time in order to ensure the sunshine quality
Appreciate your works

**Comment by roxas358** [comment]
Besides，the time interval of sampling in sunshine calculation is an important factor affecting the calculation error. In order to ensure the accuracy of the sunshine analysis results and control the error within a reasonable range, the shadow sampling time interval should not be greater than 1.0min for the calculation software using the shadow time-sharing algorithm.

For the current version，I guess the sunlightHoursResult value is something relating to the amount of sunlight vectors. So i have to set the _timeStep_ to 60 to increase the sunlight vector amount conversing unit from hour to minitue virtually. After that i need do a division by 60 to the sunlightHoursResult , and make a customed legend par to set the unit back to hour， because the default unit of legendpar of the Ladybug_Sunlight Hours Analysis component is in hour while the value is in minute in face.
 All the work is done manually. I wish you could optimize the componet about the way results calculated and the unit translation.

**Comment by roxas358** [comment]
@mostaphaRoudsari  Thanks

**Comment by mostaphaRoudsari** [comment]
@roxas358, Please post this question on the forum. Almost all the features has already exist in Ladybug. We can help you there with your questions.
