### ISSUE TITLE
Update Radiance version on Wiki to 5.2

### ISSUE THREAD

**Issue by LyleSY** [ladybug-tools/ladybug-legacy#487]
I see the wiki recommends using Radiance 5.1. 5.2 dropped in 2018 https://github.com/NREL/Radiance/releases/tag/5.2
If 5.2 works and/or is better, can the wiki be updated to point to 5.2?

**Comment by mostaphaRoudsari** [comment]
Yes. It should work fine.

**Comment by mostaphaRoudsari** [comment]
Can you point me to the issue on Wiki?

**Comment by LyleSY** [comment]
Sure, thanks. I was look at the Install Instructions here https://github.com/ladybug-tools/ladybug-legacy/wiki/Installation-Instructions . Running further along, I see the newest version of OpenStudio is now including a yet different version of Radiance (5.0.a.12 ) and ignoring other versions and also bundling EnergyPlus 9.3. Install is either getting easier or more complicated. https://github.com/NREL/OpenStudio/releases/tag/v3.0.0  What's your take on this?

**Comment by mostaphaRoudsari** [comment]
Thank you! I updated the Wiki.

Back to OpenStudio you should ask the team. There is really no breaking change in new releases of Radiance and OpenStudio's Radiance functionality is limited to 3-phase. Not sure why they are keeping it to the older version. Probably just to be safe?

@rpg777 might be able to provide some insight here.

From our side it is fine. We are packaging our own Radiance with the new installer for the [+] plugins for reasons like this. Our use of Radiance is more advanced and relying on OpenStudio's distribution of Radiance will be tricky.
