### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by marijamiliukaite** [ladybug-tools/ladybug-legacy#493]
Have no idea what’s wrong with my grasshopper! Ladybug does not come up on rhino, and is sending me errors! Please please help! 
![8ADAC6A4-75C8-46CC-894D-5F8E99C26D45](https://user-images.githubusercontent.com/74328929/98870885-dfd04100-246b-11eb-9357-bc7f3ac8dad2.jpeg)
![D38E3E1B-7AD7-4BCD-8F2E-92AC0947437A](https://user-images.githubusercontent.com/74328929/98870896-e494f500-246b-11eb-9e18-c01a84ff110d.jpeg)
![55BCF7D0-86A8-41EB-AE07-E2FAE8953F8F](https://user-images.githubusercontent.com/74328929/98870898-e78fe580-246b-11eb-818d-716f737dd480.jpeg)
![Uploading 26CF0B4B-DD4B-4115-B3EE-29036668D95E.jpeg…]()

**Comment by mostaphaRoudsari** [comment]
Hi @marijamiliukaite, you should use the forum for support questions. Your question has already been asked and answered.

https://discourse.ladybug.tools
