### ISSUE TITLE
Bioclimatic chart Fix colors in comfort/no comfort legend

### ISSUE THREAD

**Issue by ayezioro** [ladybug-tools/ladybug-legacy#93]
Need to switch between "Comfort" and "No comfort" legend words to be consistent to the point colors in the chart. Reported by Daniel (thanks).

Chris: The description of the psychrometric has a type for the same colors. It says "red" for comfort and "red" for no comfort. The second should be "blue".

**Comment by chriswmackey** [comment]
I just wanted to note that the typo that was originally pointed out in the psych chart has been fixed.

**Comment by AntoineDao** [comment]
@chriswmackey is this issue resolved?

**Comment by ayezioro** [comment]
> @chriswmackey is this issue resolved?

As far as i remember the issue was approached and solved. But it has been a long time ago. Let me check again ...
-A.

**Comment by chriswmackey** [comment]
If @ayezioro  says it's resolved, then I'd sat it's resolved.  This is one of those that is so far back in time that I'm really not sure what the issue was about. Let's close it out.
